# Используем официальный образ Python
FROM python:3.9-slim

# Устанавливаем рабочую папку
WORKDIR /app

# Копируем список зависимостей
COPY requirements.txt .

# Устанавливаем библиотеки
RUN pip install --no-cache-dir -r requirements.txt

# Копируем основной код бота
COPY tiger_bot.py .

# Команда для запуска (используем полный путь для надежности)
CMD ["python3", "tiger_bot.py"]